### ISSUE TITLE
test: Write unit tests for FlexDrop

### ISSUE THREAD

**Issue by 0xandee** [Flex-NFT-Marketplace/Flex-Marketplace-Contract#81]
Complete the unit test of `openedition/FlexDrop.cairo`, write test cases in `openedition/tests` folder.

Use `scarb test` to run all the tests.

All test cases are required to `PASS`.

**Comment by ShantelPeters** [comment]
Hi @0xandee  can I jump on this ?

**Comment by ooochoche** [comment]
@0xandee I’m available to work on this

**Comment by kateberryd** [comment]
Hi @

**Comment by petersdt** [comment]
@0xandee  i would like to write test case for these function

**Comment by EmmanuelAR** [comment]
Heyyyy @0xandee can i work on this??? 

I will..
	1.	Review the Contract: Understand the logic and functions of FlexDrop.cairo.
	2.	Write Tests:
	•	Go to openedition/tests and create a test file for FlexDrop.cairo.
	•	Write test cases that cover all functions, including normal operation, edge cases, and failure scenarios.
	3.	Run Tests:
	•	Use the scarb test command to run all the tests.
	4.	Debug:
	•	If any tests fail, review and adjust the test cases or contract as needed, then rerun until all tests pass.
	5.	Final Steps:
	•	Ensure everything is documented and submit your work.

**Comment by CollinsC1O** [comment]
Hello @0xandee I would love to write the unit tests for this

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hi Flex Marketplace team,
I’m William from Costa Rica 🇨🇷 and member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as Full Stack engineer in several technologies (including the ones used on this project JS, and Typescript) and I am currently expanding my expertise in Rust, Cairo, and Solidity.

I’ve participated in two past OD Hack events and the StarkHack event organized by ETHGlobal.
In the StarkHack, we tried to develop an dApp to interact with NFTs in Starknet.

And that’s why I’m interested on this project, because it relates to what our old team tried back then. Also interested on learning more about your team and contribute

Profiles:
https://app.onlydust.com/u/wugalde19

https://github.com/wugalde19


### How I plan on tackling this issue
The way I’d approach this is by:
First, follow the Readme to set up the project locally.
Take a full day to really understand the logic inside of “openedition/FlexDrop.cairo” file.
Ask questions in the Telegram channel (if any).
Then, start writing tests following best practices and examples in Cairo book documentation and other projects I have contributed to before.
Run all the tests on this project to make sure all test still pass.
Open a PR with all the new tests into the “openedition/tests folder”.
And finally, after your first review of that PR, take the feedback, iterate over my implementation based on the feedback that you guys provided, and at the end of the cycle deliver good quality tests and get a good coverage % on your project

**Comment by Akinbola247** [comment]
i'd like to work on this

**Comment by EmmanuelAR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Heyyyy @0xandee can i work on this??? I’m Emmanuel Software Dev from Dojo coding and Costa Rica 


### How I plan on tackling this issue
I will..
1.⁠ ⁠Review the Contract: Understand the logic and functions the contracts 
2.⁠ ⁠Write Tests:
•⁠  ⁠Go to openedition/tests and create a test file for the contracts 
•⁠  ⁠Write test cases that cover all functions, including normal operation, edge cases, and failure scenarios.
3.⁠ ⁠Run Tests:
•⁠  ⁠Use the scarb test command to run all the tests.
4.⁠ ⁠Debug:
•⁠  ⁠If any tests fail, review and adjust the test cases or contract as needed, then rerun until all tests pass.
5.⁠ ⁠Final Steps:
•⁠  ⁠Ensure everything is documented and submit your work.

**Comment by Shoetan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am Emmanuel a returning contributor to OD hack 

### How I plan on tackling this issue
Did a similar thing here : https://github.com/carbonable-labs/carbon-protocol-v3/pull/82.

First understand how these functions works and what I expect from them 
I will write the test case in the appropriate folder 
Ensure these test cases pass

**Comment by Mario-Araya** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I have extensive knowledge in TypeScript, a solid understanding of SOLID principles, and experience with unit testing using Jest. Additionally, I’ve participated in two basecamps of StarkNet, where I learned Cairo, and I’ve completed the Starklings app, which focuses on Cairo. This background equips me with the skills to contribute effectively to both modern software development practices and emerging blockchain technologies.

### How I plan on tackling this issue
To complete the unit tests for openedition/FlexDrop.cairo, I would first review the contract's logic to fully understand its functionality and edge cases. Then, I would write comprehensive test cases in the openedition/tests folder, covering all scenarios, including positive, negative, and error-handling cases. I would use scarb test to run all the tests, ensuring that each one passes. Finally, I would make any necessary adjustments to ensure that all contract functionalities are properly validated.

**Comment by Akinbola247** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
i'm a software developer vast in cairo and typescript with 3 years+ in experience. i have experience with contract audit and overall open source contribution. as regards my contributions in the past when it comes to writing test,I contributed to writing test cases on the Satoru code base.

### How I plan on tackling this issue
I'd approach it by looking into writing unit tests, integration test, fuzz testing and also write edge cases that has potentials to break the program and proffer mitigations.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Having recently contributed by implementing tests for hints in Cairo, I am confident I can leverage that experience to tackle this issue

### How I plan on tackling this issue
- Read and understand the contracts logic
- Create adequate tests for FlexDrop
- Check that all tests "PASS" correctly before merging

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am front end developer with 6 years experience.
this will be my first time contributing to the ecosystem and i am ready to work


### How I plan on tackling this issue
I would approach this issue with following steps

Understanding the Contract: I would first review the FlexDrop.cairo contract to understand its purpose, functionality, and the various functions and state variables it contains. This understanding will help me identify the critical aspects of the contract that need to be tested.
Identifying Test Cases: Based on the contract's functionality, I would identify the key test cases that need to be covered. This may include:
Successful and failed minting of tokens
Correct token balances after minting
Successful and failed transfers of tokens
Correct token balances after transfers
Handling of edge cases, such as invalid inputs or unexpected conditions
Writing Test Cases: I would then proceed to write the test cases in the openedition/tests folder using the Scarb testing framework. Each test case would focus on a specific aspect of the contract's functionality and ensure that it behaves as expected.
Implementing Test Functions: For each test case, I would implement the necessary test functions. These functions would interact with the FlexDrop.cairo contract, execute the relevant operations, and verify the expected outcomes. The test functions should cover the following:
Setting up the necessary contract state and resources for the test
Executing the contract function(s) being tested
Asserting the expected results, such as token balances, reverted transactions, or emitted events
Running and Debugging Tests: I would use the scarb test command to run all the test cases. If any test cases fail, I would investigate the issue, debug the test functions, and the contract implementation as necessary to ensure all tests pass.
Refactoring and Improving Tests: After the initial set of tests are passing, I would review the test cases and identify opportunities for improvement, such as adding more edge cases, improving the test setup and teardown, or making the tests more readable and maintainable.
Documenting Test Cases: I would ensure that the test cases are well-documented, providing clear explanations for the purpose of each test and the expected behavior being verified.
As a frontend developer, my involvement in this task would be primarily focused on the testing aspect. However, I would also maintain a good understanding of the contract's functionality, as this knowledge would be crucial for integrating the FlexDrop.cairo contract with the frontend application.

Throughout the process, I would collaborate closely with the backend developers responsible for the contract implementation to ensure that the tests accurately reflect the desired behavior of the FlexDrop.cairo contract.

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience, primarily working with Next.js. I'm also a member of Dojo Coding, where I'm learning new things such as Cairo and Web3. This is my first time participating in an OD Hack, and I'm eager to learn and contribute to new projects.

### How I plan on tackling this issue
To address the task, I would follow these steps:

Understand the FlexDrop contract.
Write comprehensive test cases.
Ensure all tests pass.
Final verification,  I would perform a final review to ensure that the tests are comprehensive.

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Web and Systems engineer, with deep understanding of clean code principles and best practices, this has enabled me build resilient solutions backed by high quality tests and maxxed code coverage using TDD.

### How I plan on tackling this issue
- Understand the requirements for every functions
- Assert that the functions perform their tasks and meet the requirements
- Use multiple test cases to ensure every edge cases are covered.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a frontend and a blockchain developer(I write smart contract using but solidity and cairo). This has enabled me to build solutions.

### How I plan on tackling this issue
To write unit tests for the FlexDrop component using Cairo Testing, the following steps are to be followed:

Set Up Cairo Environment:
- Ensure you have Cairo installed and set up for your project. If not, refer to the Cairo documentation for installation instructions.

Create Test File:
- Create a test file name for example: test_flex_drop.cairo, in your test directory.

Write Test Cases:
- Basic Rendering: Test that FlexDrop initializes correctly without errors.
- Functionality: Test core functionality of FlexDrop, such as state changes or interactions.
- Edge Cases: Handle scenarios with different inputs or states to ensure robustness.

Run Tests:
- Use the Cairo CLI or testing tool to execute the test cases and check results.

Review Results:
- Ensure all tests pass and review any failures for issues or necessary fixes.
- Adjust the testing code and functions based on the specifics of the FlexDrop component and your project's requirements.

**Comment by LukePereyra** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I'm a Software Engineer Frontend I have experience working on React, Typescript and im learning about Cairo,  im looking for a job so i work hard for find it

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
Hello @0xandee I'm a smart contract developer

### How I plan on tackling this issue
I would approach this issue the following way:

- Understand the FlexDrop.cairo file: I'll start by thoroughly reviewing the `FlexDrop.cairo` file to understand its logic and functionalities.

- Identify test cases: I'll identify all the scenarios that need to be tested based on the functionality of `FlexDrop.cairo`.

- Write test cases: I'll write the necessary test cases in the `openedition/tests` folder, ensuring they cover both positive and negative scenarios.

- Use Scarb for testing: I'll use the `scarb test` command to run all the tests to ensure everything works as expected.

- Debug and refactor: If any test fails, I'll debug the code, make the necessary adjustments, and rerun the tests until all cases pass.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/flex-marketplace).

### My background and how it can be leveraged
I am a full-stack developer with experience in different languages, such as Python, Cairo, Solidity, and JavaScript.


### How I plan on tackling this issue
I will understand the requirements:
I'm going to write unit tests for FlexDrop.cairo in the openedition/tests folder.
I will use scarb test to run all tests and.
Ensure all test cases pass.

**Comment by LazarusAA** [comment]
Thank you for assigning me this issue. I am working on it right now.

**Comment by BlueMintino** [comment]
Hello @0xandee I would love to write the unit tests for this
